### ISSUE TITLE
likes not working

### ISSUE THREAD

**Issue by pragmatech** [Bram280/Social-media-app-pb-react#1]
First and foremost, bravo! and thanks for sharing your work.

As per title of this, the liking feature doesn't seem to be hitting my fly.io pocketbase instance. 

Fwiw, I hope to translate some of this into solidjs running in vite. You might find the lighter feel of that worthwhile.

Thanks again,
Darren

**Comment by Bram280** [comment]
Hey thanks for checking it out.
It should work. (It works for me on my local instance)
Make sure that your likes table is correct and that you have also set a unique index and that the API rules are set correct.
<img width="505" alt="image" src="https://github.com/Bram280/Social-media-app-pb-react/assets/93585520/c4f189b2-f3e6-47be-be37-5ca6bec8cd7c">
<img width="505" alt="likes_API_rules" src="https://github.com/Bram280/Social-media-app-pb-react/assets/93585520/dc906dbe-fbc8-454c-bb0f-271b0d94264f">
This is what it should look like.
I was using pocketbase v0.22.10 or v0.22.09 I believe.
I don't know about fly.io specifically.
If you followed the tutorial on Medium I recommend to use the following repo:  [Tutorial github](https://github.com/Bram280/Social-media-app-pb-react-medium) , they are probably the same but I am not completely sure.

I hope this helped and good luck in translating it into solidjs :).
